In [1]:
import torch
import numpy as np

Intro a PyTorch y al final unas conclusiones de acuerdo a lo conceptos de cada celda

**1. Similitud de algunos procesos básicos entre NumPy y PyTorch**

In [4]:
# Sumando arrays con np

a = np.array([7, 2])
b = np.array([8, 4])

c = a + b
c

array([15,  6])

In [5]:
# Ahora con PyTorch la misma operacion de arrays

a = torch.tensor([7, 2])
b = torch.tensor([8, 4])

c = a + b
c

tensor([15,  6])

Se Puede Pasar de PyTorch a np y viceverza

In [6]:
a = torch.tensor([7, 5])

# llamando la variable a con np
a.numpy()

array([7, 5], dtype=int64)

In [7]:
# el caso contrario
a = np.array([4, 8])

torch.from_numpy(a)

tensor([4, 8], dtype=torch.int32)

Los datos en las 2 librerias se almacenan de la misma manera y no hay costo palpable de rendimiento. PyTorch se ajusta a las bases que ha cimentado NumPy (mas antigua).

**2. Tensores**

Se podría decir que los tensores son una especie de contenedores de números que pueden tener n-dimensiones. 
    

 - Creando un Tensor

In [11]:
torch.tensor([[7, 4], [5, 1]])

tensor([[7, 4],
        [5, 1]])

In [12]:
#Un Tensor tipo Float
torch.FloatTensor([[7, 4], [5, 1]])

tensor([[7., 4.],
        [5., 1.]])

In [13]:
#Se puede definir el tipo de tensor, en este caso un boolean
torch.tensor([[1, 2], [2, 1]], dtype=torch.bool)

tensor([[True, True],
        [True, True]])

> En general se pueden crear una amplia gama de tensores al ser de multiples dimensiones, por ejemplo matrices aletatorias sin la necesidad de hacerlas manualmente.

In [16]:
torch.rand(4, 3)

tensor([[0.7249, 0.9664, 0.1503],
        [0.5632, 0.0220, 0.7157],
        [0.0386, 0.0512, 0.2396],
        [0.8824, 0.0411, 0.5275]])

In [17]:
# Una matriz random hech de unos
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

- Operaciones entre tensores con PyTorch

In [21]:
x = torch.tensor([[7, 6], [4, 2]])
print(x)

#suma de tensores
print(f'sum: {x.sum()}')

tensor([[7, 6],
        [4, 2]])
sum: 19


Transponer tensores

In [22]:
# transponiendo un tensor 2D
x.t()

tensor([[7, 4],
        [6, 2]])

In [23]:
#Obteniendo la forma(shape) de cada dimension
x.size()

torch.Size([2, 2])

Cuando se realizan operaciones entre tensores generalemnte se forma uno nuevo:

In [28]:
y = torch.tensor([[1, 2], [5, 1]])
z = x.add(y)
z

tensor([[8, 8],
        [9, 3]])

In [29]:
# Se puede hacer in-place (de forma local) con el mismo resultado
# casi todas las operaciones se pueden hacer de esta forma (nombre de la operacion mas un _)
x.add_(y)
x

tensor([[8, 8],
        [9, 3]])

# Conclusiones

Algunas consideraciones finales del por que puede ser una ventaja trabajar con PyTorch: 

**PyTorch se puede correr en GPU`s por lo que lo hace muy potente a la hora de trabajar con modelos que necesiten muchos datos (a comparación de NumPy).** 

In [32]:
#Para saber si hay GPU disponible. Google colab ofrece en sus servicios GPUs con las que se puede trabajar gratuitamente.
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cpu')

>Los tensores se pueden guardar en CUDA para trabajarlos desde ahi. No se permite hacer operaciones entre Tensores GPU y CPU 

Tiene un diferenciador llamado **Autograd** el cual impulsa y optimiza el entrenamiento de las redes neuronales.
Recordemos que las redes neuronales (NN) son una colección de funciones anidadas que se ejecutan en algunos datos de entrada (inputs). Estas funciones están definidas por parámetros (que consisten en pesos (weights) y sesgos (biases), que en PyTorch se almacenan en tensores.

El conjunto de herramientas para construir redes neuronales (NN) es muy robusto e incluye varios paquetes para trabajar con texto (NLP) o imagenes

Es importante tener claros conceptos generales y como se nombran en inglés.

Como Bonus se puede mencionar La discrepancia de tamaño entre los tensores ocurre con frecuencia y (casi siempre) es fácil de solucionar:

In [33]:
a = torch.ones(2, 2) 
b = torch.ones(1, 3)
a * b

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [35]:
a.size()

torch.Size([2, 2])

In [36]:
b.size()

torch.Size([1, 3])

Se pueden Imprimir los tamaños para estar completamente seguro de las operaciones que se pueden hacer. 

**A parte de PyTorch existen otras opciones muy validas como Tensorflow o Keras, para ampliar el espectro no estaría de mas revisarlas despues de tener bases solidas con Pytorch que considero en este repo, aunque "nunca hay que casarse con una sola tecnología!!**